### ISSUE TITLE
Can't gem install sinatra-synchrony

### ISSUE THREAD

**Issue by geeksam** [kyledrake/sinatra-synchrony#1]
Was gonna do a quick 'hello world' benchmarking between this and node while my coworkers prolonged an insufferable meeting, but they wrapped up before I could figure out how to install.  Is this on a different source than rubygems?

**Comment by kyledrake** [comment]
Sorry, I hadn't published it. It's now pushed, try it now.

I will have more time to work on this soon.. apologies!
