### ISSUE TITLE
can't install using bundler --pre

### ISSUE THREAD

**Issue by mschneider** [kyledrake/sinatra-synchrony#10]
The gem spec published to rubygems.org for version 0.1.0.beta.3 is invalid.
`ruby -ropen-uri -rpp -e 'pp Marshal.load(open("https://rubygems.org/api/v1/dependencies?gems=sinatra-synchrony"))'`

Fix is described here https://github.com/carlhuda/bundler/issues/1235

**Comment by dylanvee** [comment]
+1 https://github.com/carlhuda/bundler/issues/1314

This issue is preventing me from deploying my app on Heroku. Yanking 0.1.0.beta.3 would do the trick.

**Comment by dylanvee** [comment]
Looks like this got fixed, bundler --pre isn't choking anymore. Thanks!

**Comment by mschneider** [comment]
Same here.
