### ISSUE TITLE
Classic app won't start up when async-rack is required

### ISSUE THREAD

**Issue by hakanensari** [kyledrake/sinatra-synchrony#12]
The following won't start up when async-rack is required.

I pried around a little in async-rack's source. Something is messing up in its autoloading.

``` ruby
require 'sinatra'
require 'sinatra/synchrony'
require 'thin'

get '/' do
  'hello, everyone'
end
```

I'm not sure about the part of async-rack being needed for logging. Would be awesome if you could add a test for that to clarify.

And yes, it would have been awesome if I could have submitted a failing spec instead of the above code!

**Comment by kyledrake** [comment]
The async-rack inclusion is discussed here:

https://github.com/kyledrake/sinatra-synchrony/issues/8

Could you provide the error message you are receiving?

**Comment by hakanensari** [comment]
```
/Users/hakanensari/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.2.6/lib/sinatra/base.rb:1290:in `detect_rack_handler': Server handler (thin,mongrel,webrick) not found. (RuntimeError)
    from /Users/hakanensari/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.2.6/lib/sinatra/base.rb:1230:in `run!'
    from /Users/hakanensari/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.2.6/lib/sinatra/main.rb:25:in `block in <module:Sinatra>'
```

I'll take a look at the other thread when I get some down time.

**Comment by Zapotek** [comment]
Same as @hakanensari.

**Comment by kyledrake** [comment]
I'm taking a look at this today. This was re-introduced because logging didn't work without it. It works fine with classy apps, so if you need an immediate workaround I highly recommend that.

**Comment by kyledrake** [comment]
After performing an audit, I believe that the logging issue was related to a shared logger getting loaded before Rack::FiberPool does, somewhere deep in the initial Rack code. Since default logging is kindof dumb anyways, and adding "use Rack::CommonLogger" to your app fixes the problem, and async-rack is kindof a hacky pile-o-crap that's eventually going to lose sync with Rack and cause problems, I've decided to pull it and recommend that people add logging directly instead. Sorry for the delay in doing this, it's been busy over at Geoloqi!

Please let me know if this resolves the problem for you (I've pushed this to 0.2.1), and I will close this bug.

**Comment by Zapotek** [comment]
I actually I have a modular app and this exception is thrown on the first visit:

```
[2011-09-14 21:39:54] ERROR NoMethodError: undefined method `call' for nil:NilClass
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/rack/fiber_pool.rb:24:in `rescue in block in call'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/rack/fiber_pool.rb:20:in `block in call'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:48:in `call'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:48:in `block (3 levels) in initialize'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in `loop'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in `block (2 levels) in initialize'
```

And this on the subsequent ones:

```
[2011-09-14 21:44:08] ERROR FiberError: fiber called across threads
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:75:in `resume'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:75:in `spawn'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-fiber_pool-0.9.2/lib/rack/fiber_pool.rb:28:in `call'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.2.1/lib/sinatra/base.rb:1245:in `block in call'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.2.1/lib/sinatra/base.rb:1276:in `synchronize'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.2.1/lib/sinatra/base.rb:1245:in `call'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/content_length.rb:13:in `call'
/home/zapotek/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/handler/webrick.rb:52:in `service'
/home/zapotek/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/home/zapotek/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/home/zapotek/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

**Comment by kyledrake** [comment]
@Zapotek, you can't use Webrick here, you need to use an EventMachine-aware server such as Thin or Rainbows w/EM.

Either:
rackup -s thin
or
ruby app.rb -s thin

**Comment by Zapotek** [comment]
Sorry about that, I switched to the wrong branch before testing.
it's working fine now, thanks for taking care of this and best of luck with Geoloqi. :)

**Comment by kyledrake** [comment]
Thanks! Glad I could help.

**Comment by hakanensari** [comment]
Awesome, I'll go ahead and close this issue.

Now, if someone only wrote an up-to-date em + synchrony driver for Postgres ;-) cc @igrigorik

**Comment by kyledrake** [comment]
@hakanensari, if you really want to get hardcore with app performance, I would also suggest looking into some of the power NoSQL solutions forming out there. MongoDB and Riak are a few examples, my personal favorite right now is Cassandra. All of these have driver support for the EM-Synchrony fiber wrappers by providing async calls. The reason I mention is that you will get a parallelism boost from this, but your next bottleneck may be the database itself.

Just throwing that out there as food for thought. Glad this resolved your problem!

**Comment by dylanvee** [comment]
@hakanensari - I've had pretty good luck with https://github.com/leftbee/em-postgresql-adapter. It's not as widely used or actively developed as I'd like, but it supports ActiveRecord 3.

**Comment by hakanensari** [comment]
@dylanvee, project looks comatose but will check out.

@kyledrake, I'm somesql, which I suppose is like saying you're centre left in the political spectrum.
