### ISSUE TITLE
fiber called across threads

### ISSUE THREAD

**Issue by jots** [kyledrake/sinatra-synchrony#15]
I'm trying this:

``` ruby
require 'sinatra'
require 'sinatra/synchrony'
require 'open-uri'
require 'thin'

get '/' do
  data = open("http://www.google.com/")
end
```

when I hit it, I get
gems/em-resolv-replace-1.1.1/lib/em-resolv-replace.rb:36:in `resume': fiber called across threads (FiberError)

Anytime I need to resolve a name, I get this error.  Is there a workaround?

**Comment by kyledrake** [comment]
Try using em-http-request or RestClient for this. The TCPSocket overload is a crap shoot at best.

**Comment by jots** [comment]
I tried RestClient and got the same error.  I think the problem is in resolving the name.

get '/' do
  RestClient.get 'http://www.google.com'
end

gems/em-resolv-replace-1.1.1/lib/em-resolv-replace.rb:36:in `resume': fiber called across threads (FiberError)

I also tried faraday:

get '/s' do
  Faraday.get 'http://google.com'
end

gems/em-synchrony-1.0.0/lib/em-synchrony.rb:52:in `resume': fiber called across threads (FiberError)

I wonder if I just have something wonk with my system.  I'm using

ruby 1.9.2p136 (2010-12-25 revision 30365) [x86_64-linux]

**Comment by inbox256** [comment]
I am seeing the same issue using ruby-1.9.2-p290 [ x86_64 ], thin.

**Comment by kyledrake** [comment]
RestClient and Faraday without em_synchrony use the same thing, which is Net::HTTP. Try using Faraday like this:

require 'sinatra'
require 'sinatra/synchrony'
require 'faraday'
Faraday.default_adapter = :em_synchrony

get '/' do
  Faraday.get 'http://google.com'
end

**Comment by inbox256** [comment]
Yes, that is what I'm using - the sample program.  All the latest gems.

**Comment by jots** [comment]
I am having the same issue as inbox256.  example program (including Faraday.default_adapter = :em_synchrony) gives me the same error.  I also tried Sinatra::Synchrony.overload_tcpsocket! with Net:HTTP.  Kyle, what version of ruby are you using?  I'll try it out with that.

**Comment by inbox256** [comment]
Not sure if this is a clue, but synchrony seems to want eventmachine 1.0.0.beta.3, not the latest 0.12.10.

**Comment by kyledrake** [comment]
Sorry for the delay, I will try to look into this as soon as I can, been extremely busy at work.

I'm not sure what change broke things, I have this version working on a web application right now. I know that Sinatra recently had a new version so perhaps trying 1.2 is an idea for now.

**Comment by kyledrake** [comment]
I have confirmed that switching to Sinatra 1.2.7 fixes this, and using Sinatra 1.3.x breaks. I'm assuming this is related to the new streaming functionality. I will investigate further, but for the interim use Sinatra 1.2.7.

**Comment by rkh** [comment]
It's not related to the streaming API. We enable threading on Thin. `disable :threaded` to fix this.

**Comment by kyledrake** [comment]
Will do, thanks!

**Comment by kyledrake** [comment]
Sinatra-synchrony 0.3.0 has been released, which fixes this problem! It now works with Sinatra 1.3.x. Thank you all for the reports, and again my apologies for the delay.

**Comment by Frexuz** [comment]
I'm still having this issue with Sinatra 1.3.1, Synchrony 0.3.0 and Ruby 1.9.2p290.
My app is the same as in the setup instructions.

**Comment by cromulus** [comment]
FWIW, I'm having the same issue:
ruby-1.9.2-p290
faraday-0.7.6
sinatra-1.3.2
sinatra-synchrony-0.3.0

**Comment by mdemare** [comment]
Also have the same issue:

Ruby-1.9.3-p194
em-http-request (1.0.0)
eventmachine (1.0.0.beta.3)
em-synchrony (1.0.0)
sinatra (1.3.2)
sinatra-synchrony (0.3.0)

**Comment by fuzzmonkey** [comment]
Anyone else stumbling across this from google; i had the same problem and it was because i'd forgot to include thin in my Gemfile.
