### ISSUE TITLE
Classic app example doesn't work

### ISSUE THREAD

**Issue by matthewleon** [kyledrake/sinatra-synchrony#18]
Just to test this out, I created a classic app as per the readme. For what it's worth, I'm on 1.9.2 and I've added a line for bundler:

``` ruby
require 'bundler/setup'
require 'sinatra'
require 'sinatra/synchrony'

get '/' do
  'Sinatra::Synchrony is loaded automatically in classic mode, nothing needed'
end
```

Got the following response from the server:

```
NoMethodError at /
undefined method `call' for nil:NilClass
file: fiber_pool.rb location: rescue in block in call line: 24
```

**Comment by kyledrake** [comment]
What web server is running? Try using thin and see if that fixes it.

What patch level of ruby are you on? (ruby -v)

**Comment by matthewleon** [comment]
I was, admittedly, using the default WEBrick server. My fault, then. It might be worth emphasizing next to the examples or in the installation section that this only works with certain servers (yes, I know that's mentioned elsewhere in the doc, but I imagine other cretins in a hurry like me will make the same mistake).

**Comment by w-A-L-L-e** [comment]
Is fiber_pool only working with nginx because I get the same error on same line with apache and ruby 1.9.3. p250
