### ISSUE TITLE
Example application

### ISSUE THREAD

**Issue by drnic** [kyledrake/sinatra-synchrony#2]
I'm having a brain freeze.

My Gemfile:

<pre>
source :rubygems

gem 'sinatra-synchrony'
</pre>

My config.ru:

<pre>require 'rubygems'
require 'bundler'

Bundler.require

class App &lt; Sinatra::Base
  register Sinatra::Synchrony
  get '/' do
    'Hello World!'
  end
end
</pre>

But with `rackup -s thin` I get the error:

<pre>$ rackup -s thin
config.ru:7:in `<class:App>': uninitialized constant Sinatra::Synchrony (NameError)
    from config.ru:6:in `block in <main>'
    from /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/builder.rb:46:in `instance_eval'
    from /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/builder.rb:46:in `initialize'
    from config.ru:1:in `new'
</pre>

**Comment by kyledrake** [comment]
require 'sinatra/synchrony'  ?

**Comment by kyledrake** [comment]
err gem 'sinatra-synchrony', :require => 'sinatra/synchrony'

Followed the typical sinatra convention there.. not neccessarily in agreement of it. :-)

**Comment by drnic** [comment]
I found an example app to relieve me of my sense of idiocy - https://github.com/igal/sinatra-synchrony-sample

**Comment by drnic** [comment]
Ok, my Gemfile now looks like:

<pre>source :rubygems

gem 'sinatra-synchrony', :require => 'sinatra/synchrony'
gem 'daemons'</pre>

But when I request http://localhost:9292 I get the following error:

<pre>127.0.0.1 - - [05/May/2011 16:04:07] "GET / HTTP/1.1" 500 83607 0.0234
NoMethodError: undefined method `call' for nil:NilClass
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/lint.rb:48:in `_call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/lint.rb:36:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/showexceptions.rb:24:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/commonlogger.rb:18:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/async-rack-0.5.1/lib/async_rack/commonlogger.rb:14:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/content_length.rb:13:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/content_length.rb:13:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/chunked.rb:15:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/chunked.rb:15:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/thin-1.2.11/lib/thin/connection.rb:84:in `call'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/thin-1.2.11/lib/thin/connection.rb:84:in `block in pre_process'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/thin-1.2.11/lib/thin/connection.rb:82:in `catch'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/thin-1.2.11/lib/thin/connection.rb:82:in `pre_process'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/thin-1.2.11/lib/thin/connection.rb:57:in `process'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/thin-1.2.11/lib/thin/connection.rb:42:in `receive_data'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/thin-1.2.11/lib/thin/backends/base.rb:61:in `start'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/thin-1.2.11/lib/thin/server.rb:159:in `start'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/handler/thin.rb:14:in `run'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/server.rb:213:in `start'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/server.rb:100:in `start'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/bin/rackup:4:in `<top (required)>'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/bin/rackup:19:in `load'
    /Users/drnic/.rvm/gems/ruby-1.9.2-p180/bin/rackup:19:in `<main>'
</pre>


Thoughts?

**Comment by drnic** [comment]
I've put my code in this repo - https://github.com/drnic/sinatra-synchrony-example

**Comment by kyledrake** [comment]
Add this to the bottom of your config.ru:

run App

On Thu, May 5, 2011 at 4:11 PM, drnic
reply@reply.github.com
wrote:
