### ISSUE TITLE
gem install unresolved dependencies

### ISSUE THREAD

**Issue by morganp** [kyledrake/sinatra-synchrony#22]
When I tried to install I get a gem dependency error

```
gem install sinatra-synchrony
ERROR:  While executing gem ... (Gem::DependencyError)
Unable to resolve dependencies: sinatra-synchrony requires eventmachine (= 1.0.0.beta.3); em-synchrony requires eventmachine (>= 1.0.0.beta.1); em-http-request requires eventmachine (>= 1.0.0.beta.3); em-socksify requires eventmachine (>= 1.0.0.beta.4)
```

To resolve this I did:

```
gem install eventmachine --pre 
gem install eventmachine --version 1.0.0.beta.3
```

I have multiple gems installed and I am likely requiring the latest (beta4) which according to the gem spec should not be used.

**Comment by j1n6** [comment]
The solution works. thanks for noting it down.

**Comment by morganp** [comment]
I found the following to be a better work around if you are using bundler:

```
gem "sinatra-synchrony", :require => 'sinatra/synchrony', :git => 'git://github.com/kyledrake/sinatra-synchrony.git'
```

The dependancies have been updated between the latest gem release and HEAD.

**Comment by shilov** [comment]
Thanks for sharing @morganp . Would you mind explaining why the `:require => 'sinatra/synchrony'` bit is necessary?

**Comment by morganp** [comment]
@shilov, when using bundler you can use it to do all the heavy lifting of requiring the relevant gems, Only recommended for use in your own apps and not gems. This is the little bit of bundler magic for the top of your app:

```
require 'bundler/setup'
Bundler.require(:default)
```

So the require path makes bundler do `require 'sinatra/synchrony'` instead of its default `require 'sinatra-synchrony'` which is incorrect for sinatra extensions. Do ask if this is not clear.

**Comment by shilov** [comment]
Ah okay, I guess this is the part I was confused about..

```
So the require path makes bundler do require 'sinatra/synchrony' instead of
its default require 'sinatra-synchrony' which is incorrect for sinatra extensions.
```

Just to make sure I understand it correctly, I have the following in my Gemfile:

```
gem 'hiredis'
gem 'redis', git: 'git://github.com/redis/redis-rb.git', :require => ['redis', 'redis/connection/hiredis']
```

By specifying the require, I'm telling Bundler to do a require for `redis` followed by a require for the `redis/connection/hiredis` extension. Is this correct?

**Comment by morganp** [comment]
@shilov I have never used arrays with bundler :require but from what I can tell you are correct in that you are telling it to do `require 'redis'` and then `require 'redis/connection/hiredis'`

Based on [1] from http://gembundler.com/gemfile.html

```
[1] And for gems with several files to require, it's also possible to give an array to :require.
```

**Comment by kyledrake** [comment]
Sorry for the delay, I will try to sit down and go through the tickets here this weekend.

**Comment by morganp** [comment]
I think this just need a new gem version releasing as the dependancy had been fixed in github.

**Comment by kyledrake** [comment]
I have pushed a new version with the commit, let me know if it works for you and I'll close this.

Also, if anyone was interested in having commit access, let me know and I'll add you to the comitters list. I've been too busy to do any work on this unfortunately.

**Comment by morganp** [comment]
Works for me. Thanks.
