### ISSUE TITLE
new version depending on eventmachine 1.0.0.rc.4

### ISSUE THREAD

**Issue by theflow** [kyledrake/sinatra-synchrony#27]
Hello,

would you mind pushing a new version that depends on eventmachine 1.0.0.rc.4? beta4 doesn't install easily on Ubuntu 12.04.

Cheers,
Florian

**Comment by mjc-gh** [comment]
Was able to bump the version on Github. I do not have access to release a new gem version though. 

Hope this is able to help you in the interim.

**Comment by kyledrake** [comment]
I will push this and give you gem release access as soon as I get to a wifi spot! In transit right now

**Comment by kyledrake** [comment]
I have pushed to 0.4.0, which has the rc4 dependency. I will push another release when final comes out (so, never basically).
