### ISSUE TITLE
How can I deploy sinatra-synchrony app with rainbows thread mode?

### ISSUE THREAD

**Issue by geun** [kyledrake/sinatra-synchrony#28]
Hi, I'm striving to use sinatra-synchrony with rainbows. 

when sample app which in github readme run, it comes up error like this.

fiber called across threads
file: fiber_pool.rb location: resume line: 75

how can i get this?

if you don't mine, can I get sample of configure of rainbow ?

**Comment by kyledrake** [comment]
I don't recommend using Rainbows with thread mode. You should use EventMachine mode instead:

https://gist.github.com/2120107

**Comment by geun** [comment]
Thanks for reply. 
but I want to know adventage of using rainbows eventmachine mode instead of thin. 

thin is better than rainbow when I tested httperf test in localhost

when :production
worker_processes 4
worker_connections 1024
timeout 10

**Comment by kyledrake** [comment]
You use Rainbows when you want to have multiple processes, in order to utilize all of the cores on your CPU. Use either, they will both work.
