### ISSUE TITLE
Changing spec body response doesn't make spec fail

### ISSUE THREAD

**Issue by drnic** [kyledrake/sinatra-synchrony#3]
See https://github.com/kyledrake/sinatra-synchrony/blob/master/spec/synchrony_spec.rb#L22-27

If you change the response "ok" to "xxxxx" and run the specs again `rspec spec` they still pass:

<pre>$ rspec spec
.

Finished in 0.27759 seconds
1 example, 0 failures
</pre>

**Comment by kyledrake** [comment]
It's MiniTest, try this: bundle exec ruby spec/synchrony_spec.rb
I'll document how to run the tests. Any convention preferences? Perhaps a rake task?

**Comment by drnic** [comment]
Cool, that works. 

I think "rake spec" or "rake test" (with a bonus "rake" pointing to whichever you support) is the nicest UX for loading up the specs however they need to be loaded. I'll throw one together in a fork later.

## Nic 

Dr Nic Williams
Engine Yard, VP Technology
SV Ruby Club, President
http://engineyard.com
http://drnicwilliams.com
cell +1 (415) 860-2185

**Comment by kyledrake** [comment]
Great, send a pull request and I will merge it in. Thanks!

**Comment by drnic** [comment]
Closed by  [fe55f5e4cfcda07d9f6b]
