### ISSUE TITLE
async-rack is not needed

### ISSUE THREAD

**Issue by steeve** [kyledrake/sinatra-synchrony#4]
Since you are using rack-fiber_pool, async-rack is not needed.
Indeed, rack-fiber_pool is responsible for issuing the throw async when nescessary. 

Since the pattern is to yield and resume in the callback block, there is no need for async-rack, and it WILL break on you. It did on me :)

**Comment by kyledrake** [comment]
That's excellent to know. I'm curious as to how it's being used in Goliath then, which was where I discovered it. I will remove it now.

**Comment by kyledrake** [comment]
I have removed and pushed 0.0.2. Thank you!

Before I close this, I wanted to ask if you could take a moment to provide an example that breaks, so I can write a test for it to confirm what you've discovered.

**Comment by steeve** [comment]
Sorry about the delay, didn't see the response. I don't have any examples right now, as I had the issue 4-5 months ago... And maybe I'm mistaken. However, you still don't need it, that's what rack-fiber_pool is for (throw async) :)

**Comment by kyledrake** [comment]
Yep, I had this confirmed by RKH as well. Thanks again!
