### ISSUE TITLE
Doesn't quite work with OAuth2?

### ISSUE THREAD

**Issue by jdrowell** [kyledrake/sinatra-synchrony#6]
I'm trying to integrate this into an existing Sinatra app. We use OAuth2 (the 'oauth2' gem) to handle Facebook authentication. Here's a traceback of the callback (initial redirect worked fine):

TypeError - wrong argument type EventMachine::Synchrony::TCPSocket (expected File):
 /home/jdrowell/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:658:in `initialize'
 /home/jdrowell/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:658:in`new'
 /home/jdrowell/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:658:in `connect'
 /home/jdrowell/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:637:in`do_start'
 /home/jdrowell/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:626:in `start'
 /home/jdrowell/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1168:in`request'
 /home/jdrowell/.rvm/gems/ruby-1.9.2-p180/gems/faraday-0.6.1/lib/faraday/adapter/net_http.rb:51:in `call'
 /home/jdrowell/.rvm/gems/ruby-1.9.2-p180/gems/faraday-0.6.1/lib/faraday/request/url_encoded.rb:14:in`call'
 /home/jdrowell/.rvm/gems/ruby-1.9.2-p180/gems/faraday-0.6.1/lib/faraday/request.rb:88:in `run'
 /home/jdrowell/.rvm/gems/ruby-1.9.2-p180/gems/faraday-0.6.1/lib/faraday/request.rb:28:in`run'
 /home/jdrowell/.rvm/gems/ruby-1.9.2-p180/gems/faraday-0.6.1/lib/faraday/connection.rb:170:in `run_request'
 /home/jdrowell/.rvm/gems/ruby-1.9.2-p180/gems/oauth2-0.4.1/lib/oauth2/client.rb:63:in`request'
 /home/jdrowell/.rvm/gems/ruby-1.9.2-p180/gems/oauth2-0.4.1/lib/oauth2/strategy/web_server.rb:15:in `get_access_token
'
 /home/jdrowell/Work/muni/lib/auth/facebook_oauth2.rb:20:in`block in class:Muni'

where line 20 is:

```
access_token = facebook_client.web_server.get_access_token(params[:code], :redirect_uri => facebook_redirect_uri)
```

Any pointers on how to debug this? Tks.

**Comment by jdrowell** [comment]
BTW this works fine by simply commenting out "require 'sinatra/synchrony'" and "register Sinatra::Synchrony", so it's not a problem with either Sinatra or the OAuth2 gem.

**Comment by steeve** [comment]
You have to use the EM-Synchrony adapter for Faraday, instead of replacing Net::HTTP.

**Comment by kyledrake** [comment]
Yeah, try that!

Could you also file this as an issue with EM-Synchrony? It's likely a bug in their TCPSocket overload. I won't likely have the time to look into this for a week at least, but I feel that error could be pretty simple to fix (just need to compensate for a type)

**Comment by steeve** [comment]
```
Faraday::default_adapter = Faraday::Adapter::EMSynchrony
```

OR

```
conn = Faraday.new(:url => 'http://foo') do |builder|
  builder.use Faraday::Adapter::EMSynchrony
end
```
