### ISSUE TITLE
No logging with Thin

### ISSUE THREAD

**Issue by rcaught** [kyledrake/sinatra-synchrony#8]
Hi,
After changing to sinatra-synchrony I seem to have lost logging to STDERR.

I am running a classic style Sinatra app with thin as my server.  Can anybody else reproduce this problem or suggest a solution?

**Comment by kyledrake** [comment]
Did you register it before all other middleware and plugins? This is almost always the cause of things like this.

**Comment by rcaught** [comment]
I've determined the cause.  The lack of `async-rack` means that logging will not be async aware.  Bundling and requiring it fixes the problem.

https://github.com/drnic/sinatra-synchrony-example works because the `Gemfile` locks `sinatra-synchrony` at `0.0.1`, which is before this commit (https://github.com/kyledrake/sinatra-synchrony/commit/e045284a8de1d59362b01a2af7b8a4d95524c01c) removed `async-rack`.

Applying a `bundle update` on the simple example app proves that the logging stops after upgrading.

Please consider adding `async-rack` back into the `Gemfile` and the `lib/sinatra/synchrony.rb` requires!

**Comment by kyledrake** [comment]
Interesting. I was under the impression that async-rack was not neccessary here, because we are not using the async.callback stuff. Async-rack is supposed to be useful if you're using something like Sinatra-async (raggi's gem) which uses callback-oriented development. I'm assuming you're not doing this, but let me know if you are.

Could you provide me with a simple code example that demonstrates this? If this turns out to be necessary i will definitely add it back. Thank you!

**Comment by kyledrake** [comment]
Okay, I've confirmed this behavior, you are correct. I will add async-rack back to the dependencies. Thank you for the input! I'm going to add 'rcaught' to the thanks, but if you'd prefer I use your real name just let me know. Cheers

**Comment by rcaught** [comment]
Great stuff.  You can use my real name if you like, Ryan Caught.  And thanks for being so responsive!

**Comment by kyledrake** [comment]
I've pushed 0.1.0.beta.5, could you test and see if it fixes this problem for you? If it works alright, I'm pushing for a release on Friday.

**Comment by rcaught** [comment]
Not quite.  I think you still need to `require 'async-rack'` in `lib/sinatra/synchrony.rb`.

**Comment by kyledrake** [comment]
Gah, sorry about that! Try 0.1.0.beta.6

**Comment by rcaught** [comment]
Works great!  :)

**Comment by kyledrake** [comment]
Alright, I will be pushing it this week as 0.1.0 (likely tomorrow). Thanks!

**Comment by Overbryd** [comment]
Hy,

I'm running `sinatra-synchrony` on version `0.3.0` and I am having the same problem.
Was there an explizit reason why `async-rack` has been thrown out a second time?

I have a classic style app running, and thin does not log requests as expected. If I `require 'async-rack'` on top of my application, logging works again.
Now I'm not sure if this is the right way to fix this. Please give me a hint on how to fix logging.

**Update:** I've digged around in other issues, and I've found the reason why you exclude `async-rack`. I will try another logging solution and I'll post my result here.

**Update 2:** This fixed the problem without relying on `async-rack` wich is considered breaking stuff.

``` ruby
require 'sinatra'
require 'sinatra/synchrony'

use Rack::CommonLogger
```

**Comment by kyledrake** [comment]
Yes, if you need logging call Rack::CommonLogger directly, that should take care of it.
